name: Deploy to InfinityFree333

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    name: BIPIN FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to SSH server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          host: "ftpupload.net"  # Replace with your SSH host if using SSH
          username: "if0_38195008"  # Your SSH username
          password: "WBZivbyPZG3zVfc"  # SSH password
          script: |
            cd /sush05.ct.ws/htdocs/
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev --ignore-platform-reqs
