name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: deploy tetsing
        uses: actions/checkout@v4

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"   # Change to the directory you want to upload
          server-dir: /sush05.ct.ws/htdocs/  # Set FTP folder path
