name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    name: BIPIN FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: appleboy/ftp-action
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # Change to the directory you want to upload
          server-dir: /sush05.ct.ws/htdocs/  # Set the FTP folder path
