name: Deploy to Server (SSH) Through Github actions
on:
  push:
    branches:
      - main
jobs:
  Deploy-To-BCOD-Server:
    needs: Check-PHP-8-syntax
    runs-on: ubuntu-latest
    steps:
      - name: deploy webapi
        uses: appleboy/ssh-action@master
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # Change to the directory you want to upload
          server-dir: /sush05.ct.ws/htdocs/  # Set the FTP folder path
  Check-PHP-8-syntax:
    name: "Linting with overtrue/phplint"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-20.04"

        php-version:
          - "8.3"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP runtime
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"

      - name: Lint PHP files
        run: |
          curl -Ls https://github.com/overtrue/phplint/releases/download/4.5.0/phplint.phar -o /usr/local/bin/phplint
          chmod +x /usr/local/bin/phplint
          /usr/local/bin/phplint -vvv --no-cache